id: P003003
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23485
  title: དག་ཡིག་ཐོན་མིའི་དགོངས་རྒྱན།
  author: ''
  volumes:
    2111d678c7fc42278f90dabcffa5c6c3:
      image_group_id: I1KG23525
      title: ''
      volume_number: 1
      total_pages: 250
