id: P003003
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:33:44.379504
source_metadata:
  id: bdr:W1KG23485
  title: དག་ཡིག་ཐོན་མིའི་དགོངས་རྒྱན།
  author: ''
  volumes:
    2111d678c7fc42278f90dabcffa5c6c3:
      image_group_id: I1KG23525
      title: ''
      volume_number: 1
      total_pages: 250
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
